
#ifndef GENERATION_HEPEVTREADER_H
#define GENERATION_HEPEVTREADER_H

#include "Generation/IHepMCFileReaderTool.h"
#include "Generation/IVertexSmearingTool.h"
#include "Generation/IPileUpTool.h"
#include "Generation/IHepMCMergeTool.h"

#include "FWCore/DataHandle.h"

#include "GaudiAlg/GaudiAlgorithm.h"
#include "GaudiKernel/ToolHandle.h"

#include "GaudiKernel/SystemOfUnits.h"

#include "HepMC/GenEvent.h"
#include <fstream>
/* #include "HepMC/IO_HEPEVT.h" */

namespace HepMC {
  class GenEvent;
}

namespace fcc {
class MCParticleCollection;
class GenVertexCollection;
}

/**@class HepEVTReader HepEVTReader.h HepEVTReader.h
 *
 *  Reads HepEVT file formats (generated by GuineaPig, ...).
 *
 *  @author Niloufar Alipour Tehrani
 *  @version 1.0
 */

class HepEVTReader: public GaudiAlgorithm {
  friend class AlgFactory<HepEVTReader> ;

public:
  /// Constructor.
  HepEVTReader(const std::string& name, ISvcLocator* svcLoc);
  /// Initialize.
  virtual StatusCode initialize();
  /// Execute.
  virtual StatusCode execute();
  /// Finalize.
  virtual StatusCode finalize();

private:

  //*******************************************//
  std::string m_filename;
  std::ifstream m_input;
  int NHEP;
  int m_format;
  /// Handle for the genparticles to be written
  DataHandle<fcc::MCParticleCollection> m_genphandle{"genParticles", Gaudi::DataHandle::Writer, this};
  /// Handle for the genvertices to be written
  DataHandle<fcc::GenVertexCollection> m_genvhandle{"genVertices", Gaudi::DataHandle::Writer, this};
  //*******************************************//

};

#endif //GENERATION_HEPEVTREADER_H
