# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "TGZ;TBZ2;TZ")
SET(CPACK_IGNORE_FILES "/InstallArea/;/build\\..*/;/\\.svn/;/\\.settings/;\\..*project;\\.gitignore")
SET(CPACK_INSTALLED_DIRECTORIES "/afs/cern.ch/work/d/degrutto/private/FCC260315/FCC/myFCCSW;/")
SET(CPACK_INSTALL_CMAKE_PROJECTS "")
SET(CPACK_INSTALL_PREFIX "/afs/cern.ch/work/d/degrutto/private/FCC260315/FCC/myFCCSW/InstallArea/x86_64-slc6-gcc48-opt")
SET(CPACK_MODULE_PATH "/afs/cern.ch/work/d/degrutto/private/FCC260315/FCC/myFCCSW/cmake;/afs/cern.ch/work/d/degrutto/private/FCC260315/FCC/GAUDI/GAUDI_v25r2/InstallArea/x86_64-slc6-gcc48-opt/cmake;/afs/cern.ch/work/d/degrutto/private/FCC260315/FCC/GAUDI/GAUDI_v25r2/cmake;/afs/cern.ch/work/d/degrutto/private/FCC260315/FCC/GAUDI/GAUDI_v25r2/cmake/modules")
SET(CPACK_NSIS_DISPLAY_NAME "FCCSW 999.999.0")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "FCCSW 999.999.0")
SET(CPACK_OUTPUT_CONFIG_FILE "/afs/cern.ch/work/d/degrutto/private/FCC260315/FCC/myFCCSW/build.x86_64-slc6-gcc48-opt/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/afs/cern.ch/sw/lcg/contrib/CMake/2.8.12.2/Linux-i386/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "FCCSW built using CMake")
SET(CPACK_PACKAGE_FILE_NAME "FCCSW-999.999.0-Source")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "FCCSW 999.999.0")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "FCCSW 999.999.0")
SET(CPACK_PACKAGE_NAME "FCCSW")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "Humanity")
SET(CPACK_PACKAGE_VERSION "999.999.0")
SET(CPACK_PACKAGE_VERSION_MAJOR "999")
SET(CPACK_PACKAGE_VERSION_MINOR "999")
SET(CPACK_PACKAGE_VERSION_PATCH "0")
SET(CPACK_RESOURCE_FILE_LICENSE "/afs/cern.ch/sw/lcg/contrib/CMake/2.8.12.2/Linux-i386/share/cmake-2.8/Templates/CPack.GenericLicense.txt")
SET(CPACK_RESOURCE_FILE_README "/afs/cern.ch/sw/lcg/contrib/CMake/2.8.12.2/Linux-i386/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/afs/cern.ch/sw/lcg/contrib/CMake/2.8.12.2/Linux-i386/share/cmake-2.8/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TGZ;TBZ2;TZ")
SET(CPACK_SOURCE_IGNORE_FILES "/InstallArea/;/build\\..*/;/\\.svn/;/\\.settings/;\\..*project;\\.gitignore")
SET(CPACK_SOURCE_INSTALLED_DIRECTORIES "/afs/cern.ch/work/d/degrutto/private/FCC260315/FCC/myFCCSW;/")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/afs/cern.ch/work/d/degrutto/private/FCC260315/FCC/myFCCSW/build.x86_64-slc6-gcc48-opt/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "FCCSW-999.999.0-Source")
SET(CPACK_SOURCE_TBZ2 "ON")
SET(CPACK_SOURCE_TGZ "ON")
SET(CPACK_SOURCE_TOPLEVEL_TAG "x86_64-slc6-gcc48-opt-Source")
SET(CPACK_SOURCE_TZ "ON")
SET(CPACK_SOURCE_ZIP "OFF")
SET(CPACK_STRIP_FILES "")
SET(CPACK_SYSTEM_NAME "x86_64-slc6-gcc48-opt")
SET(CPACK_TOPLEVEL_TAG "x86_64-slc6-gcc48-opt-Source")
SET(CPACK_WIX_SIZEOF_VOID_P "8")
