#ifndef TESTINTERFACES_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define TESTINTERFACES_MAJOR_VERSION 1
#define TESTINTERFACES_MINOR_VERSION 0
#define TESTINTERFACES_PATCH_VERSION 0
#define TESTINTERFACES_VERSION CALC_GAUDI_VERSION(TESTINTERFACES_MAJOR_VERSION,TESTINTERFACES_MINOR_VERSION)
#endif
