#ifndef TRKNEUTRALPARAMETERS_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define TRKNEUTRALPARAMETERS_MAJOR_VERSION 1
#define TRKNEUTRALPARAMETERS_MINOR_VERSION 0
#define TRKNEUTRALPARAMETERS_PATCH_VERSION 0
#define TRKNEUTRALPARAMETERS_VERSION CALC_GAUDI_VERSION(TRKNEUTRALPARAMETERS_MAJOR_VERSION,TRKNEUTRALPARAMETERS_MINOR_VERSION)
#endif
