#ifndef RECOGEOCONVERTER_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define RECOGEOCONVERTER_MAJOR_VERSION 1
#define RECOGEOCONVERTER_MINOR_VERSION 0
#define RECOGEOCONVERTER_PATCH_VERSION 0
#define RECOGEOCONVERTER_VERSION CALC_GAUDI_VERSION(RECOGEOCONVERTER_MAJOR_VERSION,RECOGEOCONVERTER_MINOR_VERSION)
#endif
