#ifndef TRKPARAMETERSBASE_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define TRKPARAMETERSBASE_MAJOR_VERSION 1
#define TRKPARAMETERSBASE_MINOR_VERSION 0
#define TRKPARAMETERSBASE_PATCH_VERSION 0
#define TRKPARAMETERSBASE_VERSION CALC_GAUDI_VERSION(TRKPARAMETERSBASE_MAJOR_VERSION,TRKPARAMETERSBASE_MINOR_VERSION)
#endif
