#ifndef GEANTFAST_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define GEANTFAST_MAJOR_VERSION 1
#define GEANTFAST_MINOR_VERSION 0
#define GEANTFAST_PATCH_VERSION 0
#define GEANTFAST_VERSION CALC_GAUDI_VERSION(GEANTFAST_MAJOR_VERSION,GEANTFAST_MINOR_VERSION)
#endif
