#ifndef SIMULATION_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define SIMULATION_MAJOR_VERSION 1
#define SIMULATION_MINOR_VERSION 0
#define SIMULATION_PATCH_VERSION 0
#define SIMULATION_VERSION CALC_GAUDI_VERSION(SIMULATION_MAJOR_VERSION,SIMULATION_MINOR_VERSION)
#endif
