#ifndef DATAOBJECTS_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define DATAOBJECTS_MAJOR_VERSION 1
#define DATAOBJECTS_MINOR_VERSION 0
#define DATAOBJECTS_PATCH_VERSION 0
#define DATAOBJECTS_VERSION CALC_GAUDI_VERSION(DATAOBJECTS_MAJOR_VERSION,DATAOBJECTS_MINOR_VERSION)
#endif
