#ifndef TESTTOOLS_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define TESTTOOLS_MAJOR_VERSION 1
#define TESTTOOLS_MINOR_VERSION 0
#define TESTTOOLS_PATCH_VERSION 0
#define TESTTOOLS_VERSION CALC_GAUDI_VERSION(TESTTOOLS_MAJOR_VERSION,TESTTOOLS_MINOR_VERSION)
#endif
