#ifndef TRKGEOMETRYUTILS_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define TRKGEOMETRYUTILS_MAJOR_VERSION 1
#define TRKGEOMETRYUTILS_MINOR_VERSION 0
#define TRKGEOMETRYUTILS_PATCH_VERSION 0
#define TRKGEOMETRYUTILS_VERSION CALC_GAUDI_VERSION(TRKGEOMETRYUTILS_MAJOR_VERSION,TRKGEOMETRYUTILS_MINOR_VERSION)
#endif
