#ifndef DETEXTENSIONS_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define DETEXTENSIONS_MAJOR_VERSION 1
#define DETEXTENSIONS_MINOR_VERSION 0
#define DETEXTENSIONS_PATCH_VERSION 0
#define DETEXTENSIONS_VERSION CALC_GAUDI_VERSION(DETEXTENSIONS_MAJOR_VERSION,DETEXTENSIONS_MINOR_VERSION)
#endif
