#ifndef RECOGEOMETRY_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define RECOGEOMETRY_MAJOR_VERSION 1
#define RECOGEOMETRY_MINOR_VERSION 0
#define RECOGEOMETRY_PATCH_VERSION 0
#define RECOGEOMETRY_VERSION CALC_GAUDI_VERSION(RECOGEOMETRY_MAJOR_VERSION,RECOGEOMETRY_MINOR_VERSION)
#endif
