#ifndef DETDESINTERFACES_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define DETDESINTERFACES_MAJOR_VERSION 1
#define DETDESINTERFACES_MINOR_VERSION 0
#define DETDESINTERFACES_PATCH_VERSION 0
#define DETDESINTERFACES_VERSION CALC_GAUDI_VERSION(DETDESINTERFACES_MAJOR_VERSION,DETDESINTERFACES_MINOR_VERSION)
#endif
