#ifndef EXAMPLES_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define EXAMPLES_MAJOR_VERSION 1
#define EXAMPLES_MINOR_VERSION 0
#define EXAMPLES_PATCH_VERSION 0
#define EXAMPLES_VERSION CALC_GAUDI_VERSION(EXAMPLES_MAJOR_VERSION,EXAMPLES_MINOR_VERSION)
#endif
