#ifndef DETDESSERVICES_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define DETDESSERVICES_MAJOR_VERSION 1
#define DETDESSERVICES_MINOR_VERSION 0
#define DETDESSERVICES_PATCH_VERSION 0
#define DETDESSERVICES_VERSION CALC_GAUDI_VERSION(DETDESSERVICES_MAJOR_VERSION,DETDESSERVICES_MINOR_VERSION)
#endif
