#ifndef RECONSTRUCTION_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define RECONSTRUCTION_MAJOR_VERSION 1
#define RECONSTRUCTION_MINOR_VERSION 0
#define RECONSTRUCTION_PATCH_VERSION 0
#define RECONSTRUCTION_VERSION CALC_GAUDI_VERSION(RECONSTRUCTION_MAJOR_VERSION,RECONSTRUCTION_MINOR_VERSION)
#endif
