#ifndef DETECTORS_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define DETECTORS_MAJOR_VERSION 1
#define DETECTORS_MINOR_VERSION 0
#define DETECTORS_PATCH_VERSION 0
#define DETECTORS_VERSION CALC_GAUDI_VERSION(DETECTORS_MAJOR_VERSION,DETECTORS_MINOR_VERSION)
#endif
