#ifndef TRKCHARGEDPARAMETERS_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define TRKCHARGEDPARAMETERS_MAJOR_VERSION 1
#define TRKCHARGEDPARAMETERS_MINOR_VERSION 0
#define TRKCHARGEDPARAMETERS_PATCH_VERSION 0
#define TRKCHARGEDPARAMETERS_VERSION CALC_GAUDI_VERSION(TRKCHARGEDPARAMETERS_MAJOR_VERSION,TRKCHARGEDPARAMETERS_MINOR_VERSION)
#endif
