#ifndef TESTALGORITHMS_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define TESTALGORITHMS_MAJOR_VERSION 1
#define TESTALGORITHMS_MINOR_VERSION 0
#define TESTALGORITHMS_PATCH_VERSION 0
#define TESTALGORITHMS_VERSION CALC_GAUDI_VERSION(TESTALGORITHMS_MAJOR_VERSION,TESTALGORITHMS_MINOR_VERSION)
#endif
